# Base configs
baseurl: "http://mchlxu.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Michael Xu Photography"
subtitle: "Creating is my passion!"
author: "Michael Xu"
bio: "I am a filmmaker based in Los Angeles. Currently pursuing my film major at California State University, Long Beach. In addition, I also enjoy making music, esplecially playing the guitar"
publicise: "<a href=\"https://instagram.com/mchl.xu\">follow me on instagram</a> ;)"
web_design: "MX"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ramswarooppatra"
  instagram: "https://www.instagram.com/ramswarooppatra"
  dribbble: "https://dribbble.com/ramswaroop"
  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
  github: "https://www.github.com/ramswaroop"
  
